### ISSUE TITLE
Tavis CI unit test instability

### ISSUE THREAD

**Issue by PhilMFischer** [virtualsatellite/VirtualSatellite4-Core#320]
Travis Ci bailed out on unit tests

``
testUndo(de.dlr.sc.virsat.project.resources.command.CreateSeiResourceAndFileCommandTest)  Time elapsed: 30.007 s  <<< ERROR!
4186
org.junit.runners.model.TestTimedOutException: test timed out after 30 seconds
4187
	at java.lang.Object.wait(Native Method)
4188
	at java.lang.Object.wait(Object.java:502)
4189
	at org.eclipse.core.internal.jobs.ThreadJob.waitForRun(ThreadJob.java:316)
4190
	at org.eclipse.core.internal.jobs.ThreadJob.joinRun(ThreadJob.java:205)
4191
	at org.eclipse.core.internal.jobs.ImplicitJobs.begin(ImplicitJobs.java:95)
4192
	at org.eclipse.core.internal.jobs.JobManager.beginRule(JobManager.java:297)
4193
	at org.eclipse.core.internal.resources.WorkManager.checkIn(WorkManager.java:124)
4194
	at org.eclipse.core.internal.resources.Workspace.prepareOperation(Workspace.java:2243)
4195
	at org.eclipse.core.internal.resources.Resource.delete(Resource.java:732)
4196
	at org.eclipse.core.internal.resources.Resource.delete(Resource.java:722)
4197
	at de.dlr.sc.virsat.project.structure.VirSatProjectCommons.removeFolderStructure(VirSatProjectCommons.java:206)
4198
	at de.dlr.sc.virsat.project.resources.VirSatResourceSet.removeStructuralElementInstanceResource(VirSatResourceSet.java:576)
4199
	at de.dlr.sc.virsat.project.resources.command.CreateSeiResourceAndFileCommand$2.run(CreateSeiResourceAndFileCommand.java:93)
4200
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2295)
4201
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2322)
4202
	at de.dlr.sc.virsat.project.resources.command.CreateSeiResourceAndFileCommand.undo(CreateSeiResourceAndFileCommand.java:98)
4203
	at org.eclipse.emf.workspace.EMFCommandOperation.doUndo(EMFCommandOperation.java:153)
4204
	at org.eclipse.emf.workspace.AbstractEMFOperation.undo(AbstractEMFOperation.java:370)
4205
	at org.eclipse.core.commands.operations.DefaultOperationHistory.doUndo(DefaultOperationHistory.java:406)
4206
	at org.eclipse.core.commands.operations.DefaultOperationHistory.undo(DefaultOperationHistory.java:1154)
4207
	at org.eclipse.emf.workspace.impl.WorkspaceCommandStackImpl.undo(WorkspaceCommandStackImpl.java:255)
4208
	at de.dlr.sc.virsat.project.editingDomain.VirSatWorkspaceCommandStack.undo(VirSatWorkspaceCommandStack.java:107)
4209
	at de.dlr.sc.virsat.project.resources.command.CreateSeiResourceAndFileCommandTest.testUndo(CreateSeiResourceAndFileCommandTest.java:95)
4210
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
4211
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
4212
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
4213
	at java.lang.reflect.Method.invoke(Method.java:498)
4214
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
4215
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
4216
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
4217
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
4218
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
4219
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
4220
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
4221
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
4222
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
4223
	at java.lang.Thread.run(Thread.java:748)
``

on

``
8.01s
$ git clone --depth=50 --branch=development https://github.com/virtualsatellite/VirtualSatellite4-Core.git virtualsatellite/VirtualSatellite4-Core
936
Cloning into 'virtualsatellite/VirtualSatellite4-Core'...
937
Checking out files: 100% (5494/5494), done.
938
$ cd virtualsatellite/VirtualSatellite4-Core
939
$ git checkout -qf 394ae8356218a0d135ff9db97916b792cd9dc379
``

**Comment by SaMuellerDLR** [comment]
Should be adressed by #402
