### ISSUE TITLE
Concurrent Modification Exception in History Listener

### ISSUE THREAD

**Issue by PhilMFischer** [virtualsatellite/VirtualSatellite4-Core#656]
The historylistener is working on a list of emf resources which apparently changes in the background.
Therefore the list needs to be accessed in a different way to avoid this error.

The rpoblem appeared in connection with implementing new SWTBot test cases.

`!ENTRY de.dlr.sc.virsat.project 4 0 2020-06-19 08:21:12.083
!MESSAGE Failed to listen to post command event on the command stack! 
!STACK 0
java.util.ConcurrentModificationException
	at org.eclipse.emf.common.util.AbstractEList$EIterator.checkModCount(AbstractEList.java:751)
	at org.eclipse.emf.common.util.AbstractEList$EIterator.doNext(AbstractEList.java:699)
	at org.eclipse.emf.common.util.AbstractEList$EIterator.next(AbstractEList.java:685)
	at de.dlr.sc.virsat.project.editingDomain.VirSatTransactionalEditingDomain$1.historyNotification(VirSatTransactionalEditingDomain.java:625)
	at org.eclipse.core.commands.operations.DefaultOperationHistory$2.run(DefaultOperationHistory.java:875)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.commands.operations.DefaultOperationHistory.notifyListeners(DefaultOperationHistory.java:864)
	at org.eclipse.core.commands.operations.DefaultOperationHistory.notifyDone(DefaultOperationHistory.java:930)
	at org.eclipse.core.commands.operations.DefaultOperationHistory.execute(DefaultOperationHistory.java:511)
	at org.eclipse.emf.workspace.impl.WorkspaceCommandStackImpl.doExecute(WorkspaceCommandStackImpl.java:208)
	at org.eclipse.emf.transaction.impl.AbstractTransactionalCommandStack.execute(AbstractTransactionalCommandStack.java:165)
	at de.dlr.sc.virsat.project.editingDomain.VirSatWorkspaceCommandStack.lambda$2(VirSatWorkspaceCommandStack.java:175)
	at de.dlr.sc.virsat.project.editingDomain.VirSatWorkspaceCommandStack.lambda$0(VirSatWorkspaceCommandStack.java:73)
	at de.dlr.sc.virsat.project.editingDomain.VirSatTransactionalEditingDomain.lambda$10(VirSatTransactionalEditingDomain.java:1014)`

**Comment by SaMuellerDLR** [comment]
Fixed in #642
